### ISSUE TITLE
The Autoscaler pod isn't tied to the on-demand node yet.

### ISSUE THREAD

**Issue by thienhaole92** [bocan/my-aws-eks#23]
This issue I think you can use node selector to run Autoscaler pod on on-demand node
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    node.kubernetes.io/lifecycle=normal
    ```
